FRAME_DIR_LIST = { "../../../doxyrest_b/doxyrest/frame/cfamily", "../../../doxyrest_b/doxyrest/frame/common" }
FRAME_FILE = "index.rst.in"
INPUT_FILE = "doxygen/xml-dir/index.xml"
OUTPUT_FILE = "rst-dir/index.rst"
INTRO_FILE = "page_index.rst"
SORT_GROUPS_BY = "title"
GLOBAL_AUX_COMPOUND_ID = "group_global"
LANGUAGE = c
VERBATIM_TO_CODE_BLOCK = "c"
ESCAPE_ASTERISKS = true
ESCAPE_PIPES = true
ESCAPE_TRAILING_UNDERSCORES = true
PROTECTION_FILTER = "protected"
EXCLUDE_EMPTY_DEFINES = true
EXCLUDE_PRIMITIVE_TYPEDEFS = true
SHOW_DIRECT_DESCENDANTS = true
TYPEDEF_TO_USING = true
ML_PARAM_LIST_LENGTH_THRESHOLD = 80