; ****************************************************************************
; MSEpro Code Generator v.3.0.7145.22606 built at 25.07.2019 12:33:33
; File : levels.inc                                                          
; ****************************************************************************

LEVELS_INC	.EQU	(1)

; Reset Initialization Level
LvReset .equ 1

; TimeMachine 1 ms Level CSW
LvCtrlSW1ms .equ 2

; TimeMachine 10 ms Level CSW
LvCtrlSW10ms .equ 3

; TimeMachine 100 ms Level CSW
LvCtrlSW100ms .equ 4

; TimeMachine 1 sec Level CSW
LvCtrlSW1sec .equ 5

; Start Level (Data loaded)
LvStart .equ 6

; Stop Level (prepare Data)
LvStop .equ 7

	

	
		

		

		


	

